module.exports=[
  {
    'imgPath':"../icons/popSci.png"
  },
  {
    'imgPath':"../icons/resue.png"
  },
  {
    'imgPath':'../icons/catPaw.png'
  },
  {
    'imgPath':"../icons/square.png"
  },
  {
    'imgPath':"../icons/user.png"
  }
]